source "https://github.com/CocoaPods/Specs"
platform :ios, "9.0"
use_frameworks!

def shared_pods
  
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireImage', '~> 3.1'
  pod 'MBProgressHUD', '~> 0.9.0'
  pod	'UICircularProgressRing'
  pod 'XCGLogger', '~> 4.0.0'
  pod 'SideMenuController'
  pod 'MMDrawerController'
  pod 'SCLAlertView'
  pod 'ALCameraViewController'
end

target 'LabkhandeZiba’ do
  shared_pods

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
